DROP TRIGGER IF EXISTS audit_event_snapshot_guard ON audit_event;
DROP TRIGGER IF EXISTS audit_event_append_only_guard ON audit_event;
DROP TRIGGER IF EXISTS observation_append_only_guard ON observation;
DROP TRIGGER IF EXISTS result_append_only_guard ON result;
DROP TRIGGER IF EXISTS evidence_append_only_guard ON evidence;
DROP TRIGGER IF EXISTS action_append_only_guard ON action;
DROP TRIGGER IF EXISTS actor_authorization_guard ON actor;
DROP FUNCTION IF EXISTS validate_audit_actor_snapshot();
DROP FUNCTION IF EXISTS validate_actor_authorization();
DROP FUNCTION IF EXISTS forbid_row_mutation();
DROP INDEX IF EXISTS action_capture_scope_unique_idx;
DROP INDEX IF EXISTS audit_event_correlation_id_idx;
DROP INDEX IF EXISTS audit_event_request_id_idx;
DROP INDEX IF EXISTS audit_event_engagement_subject_idx;
DROP INDEX IF EXISTS audit_event_engagement_occurred_at_idx;
DROP INDEX IF EXISTS finding_evidence_action_ids_idx;
DROP INDEX IF EXISTS finding_affected_entity_ids_idx;
DROP INDEX IF EXISTS finding_engagement_promoted_at_idx;
DROP INDEX IF EXISTS finding_engagement_status_severity_idx;
DROP INDEX IF EXISTS observation_result_idx;
DROP INDEX IF EXISTS observation_action_idx;
DROP INDEX IF EXISTS observation_entity_observed_at_idx;
DROP INDEX IF EXISTS result_action_created_at_idx;
DROP INDEX IF EXISTS result_engagement_created_at_idx;
DROP INDEX IF EXISTS entity_merged_into_idx;
DROP INDEX IF EXISTS entity_engagement_kind_last_seen_idx;
DROP INDEX IF EXISTS action_target_lookup_idx;
DROP INDEX IF EXISTS action_engagement_parse_status_idx;
DROP INDEX IF EXISTS action_engagement_phase_started_at_idx;
DROP INDEX IF EXISTS action_engagement_actor_started_at_idx;
DROP INDEX IF EXISTS action_engagement_started_at_idx;
DROP INDEX IF EXISTS evidence_engagement_sha256_idx;
DROP INDEX IF EXISTS evidence_engagement_created_at_idx;
DROP INDEX IF EXISTS actor_engagement_token_hash_idx;
DROP INDEX IF EXISTS actor_engagement_handle_idx;
DROP INDEX IF EXISTS actor_engagement_kind_idx;
DROP INDEX IF EXISTS engagement_status_created_at_idx;
DROP VIEW IF EXISTS audit;
DROP TABLE IF EXISTS audit_event;
DROP TABLE IF EXISTS finding;
DROP TABLE IF EXISTS observation;
DROP TABLE IF EXISTS result;
DROP TABLE IF EXISTS action;
DROP TABLE IF EXISTS evidence;
DROP TABLE IF EXISTS entity;
DROP TABLE IF EXISTS actor;
DROP TABLE IF EXISTS engagement;
DROP TYPE IF EXISTS finding_severity;
DROP TYPE IF EXISTS entity_key_type;
DROP TYPE IF EXISTS audit_subject_type;
DROP TYPE IF EXISTS audit_origin_kind;
DROP TYPE IF EXISTS action_parse_status;
DROP TYPE IF EXISTS action_phase;
DROP TYPE IF EXISTS action_initiated_by;
DROP TYPE IF EXISTS actor_role;
DROP TYPE IF EXISTS actor_kind;
